### ISSUE TITLE
Add my mod!1!!1

### ISSUE THREAD

**Issue by CowChunks** [AvilionAMillion/Nightmare-Industries#1]
i made tihs mod with mCreaotr and i want it in the minecraft pack!111 it ados toools and a new oer and dimenons with suuper col bosses and items1 it ahsd a new boss caled the e the herobrine 2 and he does a m1001000 damage!11 you can win by makeing dirt swoired that does 100190910901999999999999999 damgage! you makwe it with diurt in a craffting tablre with a stickm! If you dont add it my dad will hack you he own mojon and minecraft and migrosof and will dox you11!

**Comment by DanManT-503** [comment]
y e s
